
###
GET http://localhost:3001/contracts/2
profile_id: 2
###
GET http://localhost:3001/contracts
profile_id: 4

###
GET http://localhost:3001/jobs/unpaid
profile_id: 1

###
POST http://localhost:3001/jobs/3/pay
profile_id: 3

###
POST http://localhost:3001/balances/deposit/1
profile_id: 1
Content-Type: application/json

{
    "amount": 1000
}

###
GET http://localhost:3001/admin/best-profession?start="2020-08-15"&end="2020-08-19"

###
GET http://localhost:3001/admin/best-clients?start="2020-08-15"&end="2020-08-19"&limit=4